### ISSUE TITLE
attention mask相关问题

### ISSUE THREAD

**Issue by zwb29** [moon-hotel/BertWithPretrained#10]
在代码里(如TaskForSingleSentenseClassification.py)，attention_mask的代码好像是[0,0,0,....,1,1,1]这种形式，
`
padding_mask = (sample == data_loader.PAD_IDX).transpose(0, 1)`

我看在别的实现有的是[1,1,1,...,0,0,0]这种形式，不知道这两种方式有区别吗，谢谢！

**Comment by moon-hotel** [comment]
本质上是一样的

**Comment by zwb29** [comment]
好的谢谢，我明白了
