### ISSUE TITLE
SQuAD任务中文数据训练问题

### ISSUE THREAD

**Issue by Biaocsu** [moon-hotel/BertWithPretrained#3]
您好，非常感激您的开源！我最近在认真研读您的文章及代码。但在做SQuAD任务，使用中文数据训练遇到一些问题，如下：
1、中文数据就按照您代码来处理，char字符输入，但是会遇到tokenize去除空格情况，导致最后“答案”位置有偏移，以至于在show_result阶段True answer经常对应不上正确的答案

请问，中文数据处理代码主要有哪些地方需要修改？我也不清楚我是否其他处理有误，多谢，谢谢

**Comment by moon-hotel** [comment]
首先的话你肯定需要把现有的基于英文的示例看懂，尤其是数据预处理那块，模型本书并不太难。  如果是中文的话我觉得数据预处理和后处理的代码反而应该会简单一点，因为中文不要要像英文那样考虑每个字母的移动什么的。   你最好是自己逐一排查一下预处理后的结果，看看是不是和预期的一样。

**Comment by Biaocsu** [comment]
多谢哈，我已经解决了

**Comment by moon-hotel** [comment]
[抱拳]!
