### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasSgemm

### ISSUE THREAD

**Issue by zengjl20** [moon-hotel/BertWithPretrained#4]
sorry, i'd ask when i run TaskForSingleSentenceClassification.py, it always make an error.

Someone face the same problem and have solved it?

**Comment by moon-hotel** [comment]
This seems to be a problem with your deep learning environment, you can google this error message.

**Comment by moon-hotel** [comment]
第7个示例就是通过NSP和MLM这两个任务来对预训练模型进行追加训练
