### ISSUE TITLE
可以出一个用自己的数据集在自己构建的bert上训练的教学么

### ISSUE THREAD

**Issue by seu-xiong** [moon-hotel/BertWithPretrained#5]
每个实验都是用预训练好的参数直接导入模型中么，有那种用自己的数据集去训练一个bert的实验么，就例如第七个模型你是导入了预训练好的Bert的参数然后再训练么？

**Comment by TolicWang** [comment]
对的，第7个就是在预训练模型的基础上继续通过NSP和MLM任务进行追加训练。

**Comment by moon-hotel** [comment]
对的，第7个就是在预训练模型的基础上继续通过NSP和MLM任务进行追加训练。  今天也更新了这部分文章，https://mp.weixin.qq.com/s/2Vtxv1Wj9knEFKUyUeQ_6w
