### ISSUE TITLE
BertForPretrainingModel模型相关问题

### ISSUE THREAD

**Issue by kingbone9** [moon-hotel/BertWithPretrained#8]
CE里面ignore_index设的是-1，送入的mlm_label没有被mask的位置是0，是不是应该把ignore_index改为0

**Comment by moon-hotel** [comment]
确实有问题，感谢提醒已修正。

**Comment by gaozhanfire** [comment]
> 确实有问题，感谢提醒已修正。

作者你好，麻烦你在你的blog里也做一下修正吧，当时看到这里的时候疑惑了很久。不过你的文章写的蛮棒的，缺宣传。给你个star
