### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Download\\BertWithPretrained-main\\BertWithPretrained-main\\data\\PairSentenceClassification\\test.txt'

### ISSUE THREAD

**Issue by PANPANKK** [moon-hotel/BertWithPretrained#9]
请问这个test.txt是自己的预测 数据嘛

**Comment by moon-hotel** [comment]
是的，一共是train,val和test三部分

**Comment by PANPANKK** [comment]
您好您好，很感谢您的回复。我下载了数据集，然后执行了format.生成了这三个数据集。如果说我想用自己的数据集训练是不是也要执行这个文件来生成这三个数据集呢



发自我的iPhone


------------------ Original ------------------
From: 月来客栈 ***@***.***&gt;
Date: Mon,Jun 6,2022 10:25 PM
To: moon-hotel/BertWithPretrained ***@***.***&gt;
Cc: darcy JJJ ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [moon-hotel/BertWithPretrained] FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Download\\BertWithPretrained-main\\BertWithPretrained-main\\data\\PairSentenceClassification\\test.txt' (Issue #9)





 
是的，一共是train,val和test三部分

**Comment by moon-hotel** [comment]
客气，不用。  这个format只是用来格式化我用到的这个数据集。 你自己的话只需要处理成对应的格式就行

**Comment by PANPANKK** [comment]
您好您好，我发现如果是自己的数据集仅仅弄成对应的格式还不行。因为您那个format生成了三个test_None.pt，val_None.pt train_None.pt文件，想问问您如果说我自己的数据集，我应该怎么改这三个.pt文件嘞



发自我的iPhone


------------------ Original ------------------
From: 月来客栈 ***@***.***&gt;
Date: Tue,Jun 7,2022 8:32 AM
To: moon-hotel/BertWithPretrained ***@***.***&gt;
Cc: darcy JJJ ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [moon-hotel/BertWithPretrained] FileNotFoundError: [Errno 2] Nosuch file or directory:'D:\\Download\\BertWithPretrained-main\\BertWithPretrained-main\\data\\PairSentenceClassification\\test.txt'(Issue #9)





 
客气，不用。  这个format只是用来格式化我用到的这个数据集。 你自己的话只需要处理成对应的格式就行

**Comment by PANPANKK** [comment]
Key bert/encoder/embedding_hidden_mapping_in/kernel not found in checkpoint
您好，我那个问题解决了，谢谢。目前是这个问题，还想请教下，这个是我在使用albert时候出现的问题，不知道怎么弄了。也查不出错的原因。我在使用albert模型时主要是更改了model的参数”albert“，预训练模型都是albert的模型文件，
不知道问题出在哪里，


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "moon-hotel/BertWithPretrained"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 晚上6:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [moon-hotel/BertWithPretrained] FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Download\\BertWithPretrained-main\\BertWithPretrained-main\\data\\PairSentenceClassification\\test.txt' (Issue #9)





 
这3个文件是根据原始文件名和参数组合成的一个预处理结果的文件，这样的话只要参数不变，那么每次运行模型时就不用进行预处理 了，直接使用上次预处理保存的结果就是

**Comment by moon-hotel** [comment]
看起来你这个该参数是修改了某一层，导致修改后那一层的参数和预训练的参数对应不上（可能是顺序问题什么的），你可以先把预训练模型的参数名称和形状打印出来，再把你网络模型的参数名称和形状打印出来，两边对比一下。
